nextras/orm

src/Bridges/NetteDI/OrmExtension.php
OrmExtension: fixed typo - setupMetadataParaserFactory -> setupMetadataParserFactory
=> OrmExtension: fixed typo

src/Entity/AbstractEntity.php
=> entity: add overwritable property container factory

doc/model.texy
SimpleModelFactory has parameters in this order: $cache, $repositories, $metadataParserFactory.
=> Parameter order change

doc/collection.texy, src/Collection/ArrayCollection.php, src/Collection/Helpers/ArrayCollectionHelper.php, src/Collection/ICollection.php, src/Mapper/Dbal/DbalCollection.php, src/Mapper/Dbal/QueryBuilderHelper.php, tests/cases/integration/Collection/collection.where.phpt, tests/cases/unit/Mapper/Dbal/QueryBuilderHelperTest.phpt
=> Or [closes #105]

src/Collection/Helpers/ArrayCollectionHelper.php, tests/cases/integration/Collection/collection.phpt, tests/db/array-data.php, tests/db/mysql-data.sql, tests/db/pgsql-data.sql
=> ArrayCollection: fix sorting by DateTimeImmutable

tests/cases/integration/Collection/collection.phpt, tests/db/array-data.php, tests/db/mysql-data.sql, tests/db/pgsql-data.sql
test from #218 against master branch
=> add test for collection sorting by datetimeimmutable

src/Entity/Reflection/MetadataParser.php, tests/cases/unit/Entity/Reflection/PropertyMetadata.isReadOnly().phpt
=> Fix of @property-read bug

composer.json, phpstan.neon.dist, src/Bridges/NetteDI/DIRepositoryFinder.php, src/Bridges/NetteDI/IRepositoryFinder.php, src/Bridges/NetteDI/PhpDocRepositoryFinder.php, src/Collection/EntityIterator.php, src/Collection/ICollection.php, src/Collection/MultiEntityIterator.php, src/Entity/Reflection/IMetadataParser.php, src/Entity/Reflection/IMetadataParserFactory.php, src/Entity/Reflection/MetadataParser.php, src/Entity/Reflection/MetadataParserFactory.php, src/Entity/Reflection/ModifierParser.php, src/Model/MetadataStorage.php, src/Model/Model.php, src/Model/SimpleModelFactory.php, src/Relationships/IRelationshipCollection.php, src/Repository/IRepository.php, src/Repository/IdentityMap.php, src/Repository/Repository.php
Sorry for that large ignore of missing types, there is 600+ missing types and I hope these few changes are sufficient to upgrade to new version and you can add types continually in future.
Also generics can be implemented in future, I only wanted to make as few changes as possible to get "No errors".
=> Updated to phpstan 0.12

doc/entity.texy, src/Entity/AbstractEntity.php, src/Entity/Embeddable/Embeddable.php, src/Entity/Embeddable/EmbeddableContainer.php, src/Entity/Embeddable/IEmbeddable.php, src/Entity/IEntity.php, src/Entity/IEntityAwareProperty.php, src/Entity/IProperty.php, src/Entity/IPropertyContainer.php, src/Entity/ImmutableDataTrait.php, src/Entity/Reflection/MetadataParser.php, src/Entity/Reflection/PropertyMetadata.php, src/Mapper/Dbal/DbalMapper.php, src/Mapper/Dbal/StorageReflection/StorageReflection.php, src/Mapper/Memory/ArrayMapper.php, src/Model/MetadataStorage.php, src/Relationships/HasMany.php, src/Relationships/HasOne.php, src/Relationships/OneHasMany.php, tests/cases/integration/Entity/entity.embeddable.phpt, tests/cases/unit/Mapper/Dbal/StorageReflectionTest.phpt, tests/db/mssql-init.sql, tests/db/mysql-init.sql, tests/db/pgsql-init.sql, tests/inc/Currency.php, tests/inc/Money.php, tests/inc/model/book/Book.php
=> Embeddables

src/Collection/Helpers/ArrayCollectionHelper.php, src/Collection/Helpers/ConditionParserHelper.php, src/Entity/Embeddable/EmbeddableContainer.php, src/Mapper/Dbal/CustomFunctions/IQueryBuilderFilterFunction.php, src/Mapper/Dbal/CustomFunctions/IQueryBuilderFunction.php, src/Mapper/Dbal/Helpers/ColumnReference.php, src/Mapper/Dbal/QueryBuilderHelper.php, src/Mapper/Dbal/StorageReflection/StorageReflection.php, tests/cases/integration/Collection/collection.embeddables.phpt, tests/cases/unit/Collection/ConditionParserHelperTest.phpt, tests/db/mssql-init.sql, tests/db/mysql-init.sql, tests/db/pgsql-init.sql, tests/inc/model/book/BooksMapper.php
Embeddables collection filtering which was missing in the first part embeddables implementation #362.
=> Embeddables collection filtering

doc/model.texy, src/Model/IModel.php, src/Model/Model.php
Method removeAndFlush() exist only in Repository, but not in Model.
=> Missing method IModel::removeAndFlush()

doc/repository.texy
This was likely an accidental mispaste.
=> doc: fix typo

src/Collection/ArrayCollection.php, src/Collection/DbalCollection.php, src/Collection/EmptyCollection.php, src/Collection/HasManyCollection.php, src/Collection/ICollection.php, src/Collection/MutableArrayCollection.php, src/Relationships/HasMany.php, src/Relationships/OneHasMany.php, tests/cases/integration/Relationships/relationships.HasManyCollection.phpt, tests/cases/integration/Relationships/relationships.manyHasMany.collection.phpt, tests/cases/integration/Relationships/relationships.oneHasMany.collection.phpt
=> Has many collection

src/Mapper/Dbal/RelationshipMapperManyHasMany.php, src/Mapper/Dbal/RelationshipMapperOneHasMany.php, tests/cases/integration/Relationships/relationships.manyHasMany.phpt, tests/cases/integration/Relationships/relationships.oneHasMany.phpt
=> relationships: fixed counting entities when multiplied by joins 

src/Entity/Reflection/MetadataParser.php, tests/cases/unit/Entity/Reflection/MetadataParser.parseOneHasMany().phpt, tests/inc/model/book/Book.php
=> metadata parser: parse intersection type and nullable type

src/Relationships/HasOne.php, tests/cases/integration/Relationships/relationships.manyHasOne.isChanged().phpt
TypeError: Return value of Nextras\Orm\Relationships\HasOne::isModified() must be of the type boolean, null returned
=> Fix invalid return value type of HasOne::isModified().

doc/relationships.texy, src/Entity/AbstractEntity.php, src/Entity/Embeddable/Embeddable.php, src/Entity/Reflection/MetadataParser.php, src/Relationships/HasMany.php, src/Relationships/IRelationshipCollection.php, src/Relationships/ManyHasOne.php, src/Relationships/OneHasMany.php, src/Relationships/OneHasOne.php, src/Repository/RemovalHelper.php, src/TestHelper/EntityCreator.php, tests/cases/integration/Entity/entity.cloning.phpt, tests/cases/integration/Relationships/entity.relationships.phpt, tests/cases/integration/Relationships/relationships.manyHasMany.collection.phpt, tests/cases/integration/Relationships/relationships.manyHasMany.phpt, tests/db/array-data.php, tests/inc/model/tag/Tag.php
=> Relationships access only through getProperty

src/Collection/EntityIterator.php, src/Collection/MultiEntityIterator.php, src/Entity/AbstractEntity.php, src/Entity/IEntity.php, src/Relationships/HasMany.php, src/Relationships/HasOne.php, tests/cases/integration/Entity/entity.preloadContainer.phpt
=> relationships: fix trying to preload for removed entity with invalid relationship

src/Mapper/Dbal/Conventions/Conventions.php, src/Mapper/Memory/ArrayMapper.php, src/Mapper/Memory/RelationshipMapperManyHasMany.php, tests/cases/integration/Relationships/relationships.manyHasMany.collection.phpt, tests/cases/integration/Repository/repository.persistence.phpt, tests/db/mssql-data.sql, tests/db/mssql-init.sql, tests/db/mysql-data.sql, tests/db/mysql-init.sql, tests/db/pgsql-data.sql, tests/db/pgsql-init.sql, tests/inc/model/publisher/Publisher.php, tests/inc/model/tag/Tag.php
=> Array Maper fixes

src/Relationships/HasMany.php, tests/cases/integration/Relationships/relationships.oneHasMany.collection.phpt
=> relationship: rewrite hasMany::set() to avoid not-needed add & remove ops

src/Collection/DbalCollection.php, src/Collection/Functions/ConjunctionOperatorFunction.php, src/Collection/Functions/DisjunctionOperatorFunction.php, src/Collection/Functions/JunctionFunctionTrait.php, src/Collection/Helpers/DbalAnyAggregator.php, src/Collection/Helpers/DbalExpressionResult.php, src/Collection/Helpers/DbalJoinEntry.php, src/Collection/Helpers/DbalNoneAggregator.php, src/Collection/Helpers/DbalQueryBuilderHelper.php, tests/cases/integration/Relationships/relationships.manyHasMany.phpt, tests/cases/integration/Relationships/relationships.oneHasMany.phpt
This is extraction on #542 to ease the integration.
=> Joins refactoring - part 1

composer.json
See: https://getcomposer.org/doc/06-config.md#allow-plugins
=> Composer: allow-plugins

docs/entity.md
@hrach Could you do a review, please?
=> Add usage example of {wrapper} into docs [closes #553]

.github/workflows/build.yml, composer.json, src/Collection/Functions/BaseCompareFunction.php, src/Collection/Functions/CompareEqualsFunction.php, src/Collection/Functions/CompareGreaterThanEqualsFunction.php, src/Collection/Functions/CompareGreaterThanFunction.php, src/Collection/Functions/CompareNotEqualsFunction.php, src/Collection/Functions/CompareSmallerThanEqualsFunction.php, src/Collection/Functions/CompareSmallerThanFunction.php, src/Collection/Helpers/DbalExpressionResult.php, src/Collection/Helpers/DbalQueryBuilderHelper.php, src/Mapper/Dbal/Conventions/Conventions.php, src/Mapper/Dbal/Conventions/IConventions.php, tests/cases/integration/Collection/collection.where.phpt, tests/cases/unit/Mapper/Dbal/DbalValueOperatorFunctionTest.phpt, tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionWhereTest_testFilterByLocalDateTime.sql, vendor/nextras/dbal/src/SqlProcessor.php
=> collection: use proper modifiers for filtering arguments

docs/events.md
=> Update events.md void on example

src/Mapper/Dbal/Conventions/Conventions.php
=> conventions: fix ManyHasMany keys lookup on MySql with different key casing

src/Bridges/NetteDI/OrmExtension.php
PR for main branch as requested here https://github.com/nextras/orm/pull/590#issuecomment-1420928446
=> [Nette] Initialize metadata on DIC startup - main

src/Bridges/NetteDI/OrmExtension.php
When entity is created before MetadataStorage is instantiated, an exception is thrown. It happens when ORM classes are loaded lazily (e.g. via nette/di accessor). This PR fixes the issue.
=> [Nette] Initialize metadata on DIC startup - v4.0

src/Bridges/NetteDI/OrmExtension.php
Changed few things possible with Nette >= 3
=> OrmExtension refactoring

src/Collection/Aggregations/Aggregator.php, src/Collection/Aggregations/AnyAggregator.php, src/Collection/Aggregations/CountAggregator.php, src/Collection/Aggregations/NoneAggregator.php, src/Collection/Aggregations/NumericAggregator.php, src/Collection/Functions/JunctionFunctionTrait.php, tests/cases/integration/Collection/collection.aggregation.phpt, tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionAggregationTest_testRowAggregatorImposingLifting.sql
=> Fix having lifting required by row aggregator

src/Collection/DbalCollection.php, tests/cases/integration/Collection/collection.phpt, tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionTest_testCountOnLimited.sql, tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionTest_testCountOnLimitedWithJoin.sql, tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionTest_testCountStoredDbalWithoutOrderByClause.sql
=> remove order by in count queries
