- src/Entity/Reflection/AnnotationParser.php
php behaviour of `instanceof`:
http://3v4l.org/YPHYT
benchmark:
http://stackoverflow.com/a/12031401/326257
```
> Given only a class name
100,000 iterations
____________________________________________
| class_implements | Reflection | instanceOf |
|------------------|------------|------------|
| 149 ms           | 295 ms     | N/A        |
'--------------------------------------------'
```
> Fix container IProperty check

- src/Collection/Helpers/ArrayCollectionHelper.php
- tests/cases/unit/Collection/ArrayCollectionTest.phpt
Fixes
> E_RECOVERABLE_ERROR: Object of class DateTime could not be converted to string
when calling `collection->get()->orderBy('createdAt')`
> collection: fix ArrayCollection sort by DateTime

- src/Mapper/Dbal/QueryBuilderHelper.php
- tests/cases/unit/Mapper/Dbal/QueryBuilderHelperTest.phpt
> ERROR: missing FROM-clause entry for table "categorynodes"
```sql
SELECT COUNT(*) FROM "blog_post" AS "blog_post" LEFT JOIN blog_post_category AS "categoryNodes" ON ("blog_post"."id" = "categoryNodes"."post_id") WHERE categoryNodes.category_id = 3
```
needs to be quoted
```sql
WHERE "categoryNodes".category_id = 3
```
> QueryBuilderHelper: normalizeAndAddJoins quote

- src/Entity/Reflection/PropertyMetadata.php
- tests/cases/integration/Repository/repository.callbacks.phpt
- tests/cases/unit/Entity/Reflection/PropertyMetadata.isValid().phpt
- tests/inc/model/book/Book.php
There are multiple places in app where using Immutable is good idea, for example `createdAt` etc.
Similar functionality can already be achieved with `DateTime` and custom getters; this patch adds some complexity, so feel free to reject this, I won't be too salty about it. Also, I should include like 5 more test cases.
There was however an issue that allowed setting property of time `DateTime` to `DateTimeImmutable`, which definitely a bug. This patch fixes that by typecasting between mutable and immutable as defined by property metadata.
> reflection: add support for datetime immutable

- src/Mapper/Dbal/QueryBuilderHelper.php
- tests/cases/integration/Collection/collection.phpt
- tests/db/mysql-init.sql
- tests/db/pgsql-init.sql
- tests/inc/model/book/Book.php
was causing
> Nextras\Dbal\InvalidArgumentException: Redundant query parameter or missing modifier in query fragment 'SELECT [books.*] FROM [books] AS [books] WHERE [books.printed_at] IS '.
and also
> Nextras\Dbal\InvalidArgumentException: Modifier %column expects value to be string, NULL given.
> collection: fix findBy null missing operator

- src/Entity/AbstractEntity.php
- src/Entity/IEntity.php
- src/TestHelper/EntityCreator.php
getValue
> This change is a fix strictly for recent releases of PhpStorm. Php does
not count pass-by-reference as method declaration and implementations
are free to differ. PhpStorm highlights all entities as incompatible
with the interface though.
> Minor patches: getValue interface, entity creator

- src/TestHelper/TestMapper.php
- tests/cases/acceptance/MemoryManagementTest.phpt
Long running daemons and workers often call `$orm->clearIdentityMapAndCaches()` in hopes to reduce memory footprint. This test case makes sure the memory usage is roughly constant.
> Add memory leak test

- tests/cases/integration/Relationships/relationships.cyclic.phpt
- tests/cases/unit/Repository/PersistenceHelperTest.phpt
- tests/db/mysql-init.sql
- tests/db/pgsql-init.sql
- tests/inc/model/author/Author.php
After a bit more drawing this is what I came up with as the best approximation of what the previous algorithm failed to handle properly. It fails when starting from the top node.
> persistence: added new tests for relationships with indirect cycles

- src/Relationships/HasMany.php
- src/Relationships/ManyHasMany.php
- src/Relationships/OneHasMany.php
- tests/cases/integration/Relationships/relationships.manyHasMany.phpt
- tests/cases/integration/Relationships/relationships.oneHasMany.isLoaded().phpt
- tests/cases/integration/Relationships/relationships.oneHasMany.persistence.phpt
Caused by:
* https://github.com/nextras/orm/blob/cffc101fefce0b9ad258a5c4a8ac1ca2886d4a9c/src/Repository/PersistenceHelper.php#L112-L114
* https://github.com/nextras/orm/blob/cffc101fefce0b9ad258a5c4a8ac1ca2886d4a9c/src/Relationships/OneHasMany.php#L36-L42
* https://github.com/nextras/orm/blob/cffc101fefce0b9ad258a5c4a8ac1ca2886d4a9c/src/Relationships/HasMany.php#L189-L192
> Broken repeated persistence of relationships due to invalid isLoaded state

- src/Collection/EntityIterator.php
- tests/cases/unit/Collection/EntityIteratorTest.phpt
now it fails when I use STI and a relation is defined in some child class
this is just a hotifx. correct solution would probably be to find a class on which is the relation defined and call getRawValue only when `$entity instanceof $class`
> entity iterator: check if property exists

- doc/model-definition.texy
Probably in 3.0 version there was change in Mappers interface, therefore the example was outdated.
This is small documentation fix in order to make it up-to-date.
> Fix example of usage SimpleModelFactory

- src/Mapper/Dbal/StorageReflection/StorageReflection.php
I have some columns in my tables, where the column name is only **int**. Yes I know it´s bad idea but this tables was not created by me. Then if I want read from this table it everytime show error, which is on picture below.
**Error:**
**Table structure:**
> Cast everytime key as string.

- src/Mapper/Dbal/RelationshipMapperManyHasOne.php
**Generated SQL**
```
SELECT `table`.* 
FROM `table` AS `table` 
LEFT JOIN `joinTable` AS `joinTable` ON (`table`.`join_table_id` = `joinTable`.`id`) 
WHERE ((`joinTable`.`deleted` = 0)) AND (`id` IN (531, 2315))
```
**Query exception**
```
Column 'id' in where clause is ambiguous
```
**Generated SQL after bug fix**
```
SELECT `table`.* 
FROM `table` AS `table` 
LEFT JOIN `joinTable` AS `joinTable` ON (`table`.`join_table_id` = `joinTable`.`id`) 
WHERE ((`joinTable`.`deleted` = 0)) AND (`table`.`id` IN (531, 2315))
```
If you need a more information about bug just text me and I give you more specific description.
> Fixed relationship mapper bug

- src/Entity/Reflection/MetadataParser.php
- tests/inc/model/CreatedColumnTrait.php
- tests/inc/model/tagFollower/TagFollower.php
Just idea to load annotation for Entity from traits too. Example can be using TimestatemableTrait with `created...` or `update...` columns, next can be `cancelled...` etc...
First load trait, then entity class for overrides. Methods are loaded from original class with `use ***trait`.
> Loading annotation from traits too

- src/Entity/Reflection/MetadataParser.php
I started with classical bidirectional relation. 
```php
/**
* @property int     $id          {primary}
* @property Author  $author      {m:1 Author::$id}
*/
class Book extends Nextras\Orm\Entity\Entity
{}
```
Because I did a mistake (in reality, i wanted one-sided relation and i had also mistake in property) so I got exception `Book::$author has not defined a symmetric relationship in Author::$id.`
So i added oneSided property and **forgot to delete** atribute in target.
```php
/**
* @property int     $id          {primary}
* @property Author  $author      {m:1 Author::$id, oneSided=true}
*/
class Book extends Nextras\Orm\Entity\Entity
{}
```
As a result I got this exception `Modifier {m:1} in Book::$author property has unknown arguments: oneSided.`
This was really confusing because …
> Improved error message for oneSided property

- src/Relationships/OneHasMany.php
- tests/cases/integration/Repository/repository.persistence.phpt
> relationships: fixed invalidating cache after persist & before flush [closes #386]

- src/Mapper/Dbal/Conventions/Conventions.php
> conventions: always use nullable modifier to let db handle type mismatch

- doc/entity.texy
- src/Entity/AbstractEntity.php
- src/Entity/Embeddable/Embeddable.php
- src/Entity/Embeddable/EmbeddableContainer.php
- src/Entity/Embeddable/IEmbeddable.php
- src/Entity/IEntityAwareProperty.php
- src/Relationships/HasMany.php
- src/Relationships/HasOne.php
- src/Relationships/OneHasOne.php
- tests/cases/integration/Collection/collection.phpt
- tests/cases/integration/Entity/entity.nullValidation.phpt
- tests/cases/integration/Relationships/relationships.manyHasOne.phpt
- tests/cases/integration/Relationships/relationships.oneHasMany.compositePK.phpt
- tests/cases/integration/Relationships/relationships.oneHasMany.phpt
- tests/cases/integration/Relationships/relationships.oneHasMany.remove.phpt
- tests/cases/unit/Entity/AbstractEntity.repository.phpt
> relationships: make HasOne relationship lazy until entity is attached

- src/Entity/ImmutableDataTrait.php
- src/Relationships/HasOne.php
- src/Relationships/OneHasOne.php
- tests/cases/integration/Entity/entity.hasValue().phpt
- tests/cases/integration/Relationships/relationships.oneHasOne.phpt
- tests/inc/TestCase.php
- tests/inc/model/ean/Ean.php
`Entity->hasValue()` should not set value for property which does not have value yet. In most cases it will just set null and gets eventually overriden, but in case of enum wrapper which expects fixed subset of values, null (which is out of that subset) raises an exception when enum is tried to be created.
To verify issue, drop the source change in ImmutableDataTrait - included test will fail.
> Entity->hasValue() should not set null value for uninitialized property

- src/Collection/ArrayCollection.php
- src/Collection/DbalCollection.php
- src/Collection/EmptyCollection.php
- src/Collection/HasManyCollection.php
- src/Collection/ICollection.php
- src/Collection/MemoryCollection.php
- src/Relationships/IRelationshipCollection.php
- tests/cases/integration/Collection/collection.phpt
BC breaks - ICollection interface has changed
> collection: add toMemoryCollection() (BC break!)

- src/Collection/Aggregations/AnyAggregator.php
- src/Collection/Aggregations/CountAggregator.php
- src/Collection/Aggregations/IAggregator.php
- src/Collection/Aggregations/NoneAggregator.php
- src/Collection/Functions/BaseAggregateFunction.php
- src/Collection/Helpers/DbalQueryBuilderHelper.php
- tests/cases/integration/Collection/collection.aggregation.join.phpt
Merged as part of #545:
----------------
Merged as part of #546:
----------------
This PR:
Closes #541 
Closes #526
> Merging same JOINs together & introduction of independent JOINs

- src/Repository/PersistenceHelper.php
The keys returned by the `debug_backtrace()` function for each stacktrace frame are almost all optional. This PR adds the missing checks to avoid the code to crash if the keys are not present
> Add missing array key checks when using the `debug_backtrace()` function

- src/Collection/HasManyCollection.php
- src/Mapper/Dbal/DbalMapper.php
- src/Relationships/HasMany.php
- src/Relationships/IRelationshipCollection.php
- src/Repository/PersistenceHelper.php
- src/Repository/RemovalHelper.php
spl_object_id() should be bit more performant than spl_object_hash()
I found in PHP [internals communication](https://externals.io/message/79255) that there is one difference - spl_object_hash() should return same hash for equal objects. But it does not seem to be the case https://3v4l.org/pSNBF
> Use spl_object_id instead of spl_object_hash

- src/Entity/Reflection/MetadataParser.php
Allows properties with mixed type to contain null.
Also dropped the uppercase NULL, because $parsedTypes always contains only lowercase null 
https://github.com/nextras/orm/blob/2abc593a3bb7a80bdb9ad94f3e9c47ead65ea69f/src/Entity/Reflection/MetadataParser.php#L232-L233
> mixed type allows null

- docs/config-nette.md
- src/Bridges/NetteDI/OrmExtension.php
- src/Bridges/NetteDI/PhpDocRepositoryFinder.php
- tests/cases/integration/BridgeNetteDI/dic-extension-multiple.neon
- tests/cases/integration/BridgeNetteDI/dic-extension-multiple.phpt
> Ease multiple Orm extension instances initialization with connection reference

- composer.json
- src/Entity/Reflection/MetadataParser.php
- tests/cases/unit/Entity/Reflection/PropertyMetadata.isValid().phpt
This is the first part for #521: adoption of PHPStan's PhpDocParser.
For 5.0 I do not plan to introduce any more parsing features, but this should at least provide some validation consistency.
New behavior:
- **[new]** When the type is not simple enough -> exception
- **[new]** Understands (parser as a simple array) array shapes
- **[new]** Understands (parses as a simple object) object shapes
- Supports union & intersection types
- Parser all previously supported types
- Prases nullability in both forms (`?`, `|null`)
- Removes support for `scalar` type (BC break!)
> Use PhpDocParser for property parsing

- src/Collection/Aggregations/Aggregator.php
- src/Collection/Aggregations/AnyAggregator.php
- src/Collection/Aggregations/CountAggregator.php
- src/Collection/Aggregations/NoneAggregator.php
- src/Collection/Aggregations/NumericAggregator.php
- src/Collection/DbalCollection.php
- src/Collection/Expression/ExpressionContext.php
- src/Collection/Functions/BaseCompareFunction.php
- src/Collection/Functions/BaseNumericAggregateFunction.php
- src/Collection/Functions/CollectionFunction.php
- src/Collection/Functions/CompareEqualsFunction.php
- src/Collection/Functions/CompareLikeFunction.php
- src/Collection/Functions/ConjunctionOperatorFunction.php
- src/Collection/Functions/DisjunctionOperatorFunction.php
- src/Collection/Functions/FetchPropertyFunction.php
- src/Collection/Functions/JunctionFunctionTrait.php
- src/Collection/Functions/Result/DbalExpressionResult.php
- src/Collection/Helpers/DbalQueryBuilderHelper.php
- tests/.gitignore
- tests/cases/integration/Collection/Functions/FetchPropertyFunctionTest.php
- tests/cases/integration/Collection/collection.aggregation.phpt
- tests/cases/integration/Relationships/relationships.oneHasMany.phpt
- tests/cases/unit/Mapper/Dbal/DbalValueOperatorFunctionTest.phpt
- tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionAggregationTest_testMovingPrimaryTableConditionToWhenClause.sql
- tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionAggregationTest_testProperGroupByWhenLiftingNonAggregatedJoinCondition.sql
- tests/sqls/NextrasTests/Orm/Integration/Collection/CollectionHavingTest_testHavingWithSameNamedColumnsInGroupBy.sql
- tests/sqls/NextrasTests/Orm/Integration/Relationships/RelationshipManyHasManyTest_testJoinAcrossDifferentPaths.sql
- tests/sqls/NextrasTests/Orm/Integration/Relationships/RelationshipOneHasManyTest_testCountStoredOnOneHasManyRelationshipCondition.sql
- tests/sqls/NextrasTests/Orm/Integration/Relationships/RelationshipOneHasManyTest_testSameTableJoinWithImplicitAggregation.sql
It's kinda funny how this change looks simple. It took me 5 hours to come up with it
🤯💥🤯💥🤯💥🤯💥🤯💥🤯💥
> Two-phase SQL rewrites

- src/Collection/ICollection.php
- src/Entity/AbstractEntity.php
- src/Entity/IEntity.php
- src/Repository/IRepository.php
- src/Repository/Repository.php
This MR fixes deprecations with php 8.4
`Implicitly marking parameter $variable as nullable is deprecated, the explicit nullable type must be used instead`
> php84 deprecation fixes

- src/Collection/Helpers/ArrayCollectionHelper.php
- src/Entity/AbstractEntity.php
- src/Entity/PropertyWrapper/PrimaryProxyWrapper.php
- src/Entity/Reflection/MetadataParser.php
This is the first step to support property wrappers for DateTimeImmutable instances and, most importantly, also in the primary (proxied) use cases.
The next step is to abstract DateTimeImmutable handling to a property wrapper.
The next step is the introduction of the wrapper with Date (only, no time) behavior. This will be a fix for #729.
> Model PrimaryProxy modifier as property wrapper

- src/Collection/Functions/BaseCompareFunction.php
- src/Collection/Functions/CompareEqualsFunction.php
- src/Collection/Functions/CompareGreaterThanEqualsFunction.php
- src/Collection/Functions/CompareGreaterThanFunction.php
- src/Collection/Functions/CompareNotEqualsFunction.php
- src/Collection/Functions/CompareSmallerThanEqualsFunction.php
- src/Collection/Functions/CompareSmallerThanFunction.php
- src/Collection/Helpers/ArrayCollectionHelper.php
- src/Entity/AbstractEntity.php
- src/Entity/ImmutableDataTrait.php
- src/Entity/PropertyComparator.php
- src/Entity/PropertyWrapper/DateTimeWrapper.php
- src/Entity/PropertyWrapper/PrimaryProxyWrapper.php
- src/Entity/Reflection/MetadataParser.php
- src/Entity/Reflection/PropertyMetadata.php
- src/Exception/InvalidPropertyValueException.php
- tests/cases/unit/Entity/Reflection/PropertyMetadata.isValid().phpt
This is the second part that abstracts DateTime(Immutable) handling to a property wrapper. This also required a new abstraction for comparison (basic built-in comparison operators); therefore, the `PropertyComparator` is introduced. The most difficult thing here was making this property wrapper work when used in the primary-proxy modifier. 
Next step: introduce Date (only) property wrapper.
Refs #729.
> Datetime property wrapper

- src/Entity/Embeddable/Embeddable.php
- src/Entity/Embeddable/EmbeddableContainer.php
- src/Entity/Embeddable/IEmbeddable.php
> add PropertyMetadata owner of embeddable to Embeddable::onAttach (BC break!)
